### ISSUE TITLE
Conflict with dependency...Resolved versions for app (1.0.2) and test app (1.0.6) differ

### ISSUE THREAD

**Issue by sevar83** [nhaarman/mockito-kotlin#146]
Kotlin 1.0.6
Android Studio 2.3.0-canary 3

`testCompile "com.nhaarman:mockito-kotlin:1.1.0"`

> Error:Conflict with dependency 'org.jetbrains.kotlin:kotlin-stdlib' in project ':app'. Resolved versions for app (1.0.2) and test app (1.0.6) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by nhaarman** [comment]
Mockito-Kotlin depends only on `1.0.6`, so the dependency conflict should be on your side. Do you have any dependencies that depend on `1.0.2`? If so, you can try using a [ResolutionStrategy](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html) to force `1.0.6` on them.

**Comment by sevar83** [comment]
> Do you have any dependencies that depend on 1.0.2?

I guess RxKotlin is the culprit. Could you tell me how to use `ResolutionStrategy` please?

**Comment by nhaarman** [comment]
An easier way is to just depend on the stdlib yourself explicitly:

```
compile 'io.reactivex:rxkotlin:0.60.0'
compile "org.jetbrains.kotlin:kotlin-stdlib:1.0.6" // This overrides the 1.0.2 dependency in RxKotlin
testCompile  "com.nhaarman:mockito-kotlin:1.1.0"
```

Using a Resolution strategy:

```
dependencies {
    compile 'io.reactivex:rxkotlin:0.60.0'
    testCompile "com.nhaarman:mockito-kotlin:1.1.0"
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.0.6'
    }
}
```

**Comment by tasomaniac** [comment]
I had a very similar problem and I'm also familiar with this already but anyways I did it wrong. Posting here for others to find out if they have the same issue. 

We are using `kotlin-stdlib-jre7`. That's why I was forcing that dependency to be the dependency I want. But they are of course not the same and `resolutionStrategy.force` just matches if they have the same group and the name. 

So make sure that you are forcing `kotlin-stdlib` just like mentioned here.

**Comment by paulnunezm** [comment]
I've found a way to solve this issue using the following:
    testCompile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

Hope it works for you too.
