### ISSUE TITLE
any() will return null for Bitmap class

### ISSUE THREAD

**Issue by feresr** [nhaarman/mockito-kotlin#193]
```
    private var mockedBitmap: Bitmap = mock()
    private var coloravg: ColorAverageCalculator = mock {
        on { getAvgColor(any()) } doReturn "#000000"
    }

```

> java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.xxx.xxx.xxx.xxx.getAvgColor, parameter bitmap

I'm not sure what I'm doing wrong, `getAvgColor` takes a `Bitmap` as a parameter

ps: I also tried passing `mockedBitmap` to `getAvgColor()` and all it calls the actual method (tries to actually calculate the avg color of the mocked bitmap) instead of returning #000000 right away

`any<Bitmap>` does not solve the problem (same result)

**Comment by nhaarman** [comment]
`any()` will always return `null`. Make sure your `getAvgColor` is mockable so it is not executed and the NPE isn't thrown.

**Comment by feresr** [comment]
What do you mean by "Make sure your `getAvgColor` is mockable".
Mocking the method `getAvgColor` is exactly what I'm trying to achieve.
This is the method signature `fun getAvgColor(bitmap: Bitmap): String` and it won't take null as a parameter.

**Comment by nhaarman** [comment]
I'm guessing that `ColorAverageCalculator` is not an interface and is `open`:

```kotlin
open class ColorAverageCalculator {

  fun getAvgColor(bitmap: Bitmap): String {
    /* ... */
  } 
```

If `getAvgColor` is not marked `open`, Mockito cannot stub this method, and the method will be executed when you call `on { getAvgColor(any()) } doReturn "#000000"`. Since `any()` does return `null`, Kotlin's null-checking will throw the error you see.
The solution here would be to mark `getAvgColor` as `open`, or make `ColorAverageCalculator` an interface.

**Comment by vojtapol** [comment]
This can be easily fixed by using the `mock-maker-inline` extension as described in this article:

https://antonioleiva.com/mockito-2-kotlin/

No need to make the classes `open`.
