### ISSUE TITLE
Mocking Extension functions

### ISSUE THREAD

**Issue by SirWellington** [nhaarman/mockito-kotlin#198]
Is it possible to stub Kotlin extension methods?

Let's say I have an extension function:

```kotlin
fun Context.findColor(color: Int) = resources.getColor(color)
```

And I have a mock of an `Context` I would like to stub:
```kotlin
val mock = mock<Context>()

whenever(mock.findColor(color)).thenReturn(color)
```

Right now it doesn't work. Is there a way to achieve this?

**Comment by SirWellington** [comment]
I know internally, kotlin converts extension functions into static methods with receivers.

So now that I think about it, mockito cannot stub static methods. PowerMock can. But Powermock does not yet work with this version of Mockito does it?

**Comment by nhaarman** [comment]
You're right about the static methods. I haven't used PowerMock, so I wouldn't know what the status is.

**Comment by nhaarman** [comment]
Closing since the question seems to be answered.

**Comment by vivekkartha** [comment]
So extension methods cannot be supported in tests with Mockito?

**Comment by melo0187** [comment]
I'm just stumbling upon the same issue and am wondering why this has only been asked so rarely.

Tried testing a Flow in a Spring Boot service written in Kotlin and using Spring Webflux.
We are currently still using spring-boot-starter-data-mongodb instead of the reactive counterpart. This is why we have an extension function that can take whatever blocking operation and wrap it in a Mono by using Mono's `fromCallable` method. That way we can compose our reactive flows including those blocking MongoDB operations.
However I now fail to properly test this flows and afaik the reason for it is that I can't actually stub the call to the extension function.

Has anyone managed to stub Kotlin extension methods somehow when using Mockito Kotlin?
Any hint is much appreciated!

**Comment by cuichanghao** [comment]
@melo0187 
you can use mockK

**Comment by Ghedeon** [comment]
What is the status of this? Assuming that extensions are crucial in kotlin, could you confirm that `"don't use mockito with kotlin, use mockK instead"` is the official answer?

**Comment by nhaarman** [comment]
I guess the 'official' answer would be "don't mock extension functions". They're basically static functions, which Mockito does not support. Create a proper abstraction for them, or resort to tools like PowerMock or MocK.

**Comment by realdadfish** [comment]
If you have instance extension functions (which are basically syntactic sugar), you can easily use mockito-kotlin for them:

```kotlin
data class Bar(thing: Int)

class Foo {
   fun Bar.bla(anotherThing: Int): Int { ... }
}

val bar = Bar(thing = 1)
val foo = mock<Foo>()

with(foo) {
  whenever(any<Bar>().bla(any()).doReturn(3)
}

verify(foo).apply {
  bar.bla(anotherThing = 2)
}
```

**Comment by vgdomi** [comment]
> If you have instance extension functions (which are basically syntactic sugar), you can easily use mockito-kotlin for them:
> 
> ```kotlin
> data class Bar(thing: Int)
> 
> class Foo {
>    fun Bar.bla(anotherThing: Int): Int { ... }
> }
> 
> val bar = Bar(thing = 1)
> val foo = mock<Foo>()
> 
> with(foo) {
>   whenever(any<Bar>().bla(any()).doReturn(3)
> }
> 
> verify(foo).apply {
>   bar.bla(anotherThing = 2)
> }
> ```

This does not work for me, is still trying to call the real extension instead of the mocked logic

**Comment by kpl-goel** [comment]
Now we know Mickito supports static mocking. Is there a way to mock static methods?

**Comment by MartinX3** [comment]
Still an issue with 4.0.0.
(Can't test 4.1.0, they don't publish it on maven)
