### ISSUE TITLE
Mark mockito-kotlin as deprecated and point to real Kotlin mocking frameworks

### ISSUE THREAD

**Issue by vojtapol** [nhaarman/mockito-kotlin#261]
The state of mocking in Kotlin tests is sad. Everybody is always pointed to this library because they know Mockito and then they are disappointed with Kotlin in testing. This library was great during the transition period when we had no alternatives but nowadays there is pretty much zero reason to use it. Its development is slow and the author unresponsive.

Example: https://github.com/nhaarman/mockito-kotlin/issues/225
Look at how long it took to get a response and how bad the API is.

 There are also inherent design issues in Mockito itself which obviously transfer to this library as well.

**I propose adding a note to the readme of this project listing better alternatives for mocking in Kotlin to help move the Kotlin community to better direction.**

I personally recommend [MockK](http://mockk.io/) and can vouch for the author who quickly fixes bug and improves the API.

**Comment by nhaarman** [comment]
I see no reason to deprecate anything. Stuff works, projects using Mockito can't just switch to a different library, and you can't expect people familiar with Mockito to just switch to something different because you feel like it.

As for slow development, I do have a life you know.

Also, this discussion does not belong here.
