### ISSUE TITLE
`doReturn` doesn't infer the generics

### ISSUE THREAD

**Issue by BraisGabin** [nhaarman/mockito-kotlin#274]
There's a *minor* problem with `doReturn`

This code works perfectly:

```kotlin
  private val action: (String) -> List<String> = mock {
    on { invoke(any()) }.thenReturn(emptyList())
  }
```

but this one doesn't:

```kotlin
  private val action: (String) -> List<String> = mock {
    on { invoke(any()) }.doReturn(emptyList())
  }
```

But if I specify the class (`emptyList<String>()`) it works:

```kotlin
  private val action: (String) -> List<String> = mock {
    on { invoke(any()) }.doReturn(emptyList<String>())
  }
```

Version `2.0.0-RC1`.

**Comment by nhaarman** [comment]
Hm, this is due to the `OngoingStubbing<T>.doReturn(ts: List<T>)` overloads, and it only happens for `OngoingStubbing<List<T>>`.
A solution would be to phase out the `OngoingStubbing<T>.doReturn(ts: List<T>)` and replace it with `OngoingStubbing<T>.doReturnConsecutively(ts: List<T>)` or something like that.

The problem will only go away when `OngoingStubbing<T>.doReturn(ts: List<T>)` is removed, which obviously is a breaking change.

See #279
